### PR TITLE
Fix memory mapped shows old content: Issue 14

### PR DESCRIPTION
**Pull request by gamlerhart**
- Flushes / Invalidates the page cache of the written section
- Enough to fix https://github.com/lundman/ZFSin/issues/14

### CODE REVIEW

**Comment by lundman** [comment]
Thanks for looking into this. Are we considering this a temporary solution until cache update can be investigated, or a final one? What does fastfat do?

**Comment by lundman** [comment]
Looks like fastfat can sometimes call `CcCoherencyFlushAndPurgeCache()` so that could be a valid work around. The proper path seems to call either `CcCopyWriteEx()` or `CcPrepareMdlWrite()` for cached writes. Which we should probably investigate in the future.


While there, looks like we should tell cache about file size changes by using:

```
  if (CcIsFileCached(FileObject)) {
     CcSetFileSizes( FileObject, (PCC_FILE_SIZES)&FcbOrDcb->Header.AllocationSize );
```

.. or rather, update the ZFS macros `vn_has_cached_data` to use `CcIsFileCached` and `vnode_pager_setsize` to `CcSetFileSizes`.

**Comment by gamlerhart** [comment]
Thanks for the hints....I'll look into it when I've time.  (All new to me, Windows-Kernel / zfs code base ^0^)

**Comment by lundman** [comment]
I think I'll go ahead and approve of this PR, so it at least works for now, and create an Issue to make the code update cache in write.

**Pull request merged**
